name: test1
desc: test1
runbooks:
- name: test1
  desc: test1
  selectors:
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=ServiceAccount'
  - type: jsonPathSelector
    selector: '{.metadata.name}=bootstrap-signer'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=kube-system'
  doc: test/test1.md
